### ISSUE TITLE
missing access token ?

### ISSUE THREAD

**Issue by changchichung** [boojack/slash#10]
I start a  slash container by using my docker-compose.yml
```
version: '2'
services:
  slash:
    container_name: 'slash'
    image: 'stevenlgtm/slash:latest'
      #volumes:
      #- ./slash:/var/opt/slash
    restart: unless-stopped
    ports:
      - '5231:5231'
```
after running up the container , I can see the slash login page , but I find no default account/password info in README, so I choose up sign up a new account .
after I fill out the form and click apply , it just redirect to create your account page again.
and I saw some log in docker
```
{"time":"2023-07-24T08:23:09Z","method":"GET","uri":"/auth/signup?","status":200,"error":""}
{"time":"2023-07-24T08:23:10Z","method":"GET","uri":"/api/v1/workspace/profile","status":200,"error":""}
{"time":"2023-07-24T08:23:11Z","method":"GET","uri":"/api/v1/user/me","status":401,"error":"code=401, message=Missing access token"}
```

I'm wondering if there is any default account/password ? or somehow to solve the register new account problem ??
